[build]
  functions = "netlify/functions"
  publish = "public"

[dev]
  functions = "netlify/functions"
  framework = "#custom"
  targetPort = 3000 # or whatever port your dev server runs on

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
